### ISSUE TITLE
Add Merge Sort Algorithm (Hacktoberfest)

### ISSUE THREAD

**Issue by AkshatJangid787** [Ayush7-BIT/turbo-robot#268]
### Description:
I would like to contribute the implementation of the **Merge Sort algorithm** in  Java. The Merge Sort algorithm is a divide-and-conquer algorithm that sorts an array by dividing it into smaller subarrays, sorting them, and then merging them back together.

### Programming Language:
JAVA

### Why This is Needed:
This will add a new sorting algorithm to the repository and help beginners understand the Merge Sort process.

### Hacktoberfest Contribution:
This issue is created for **Hacktoberfest 2024**, and I would like to contribute as part of the event.

**Comment by Archit026** [comment]
Hey @Ayush7-BIT i want to contribute the implementation of merge sort alogithm

**Comment by Smriti-Prajapati** [comment]
Hey @Ayush7-BIT , I am interested in this issue can you assign this issue to me.

**Comment by Smriti-Prajapati** [comment]
Please merge my requests I have uploaded the code for issues before 1 week.
Please merge it Sir
Regards
Smriti
