### ISSUE TITLE
Add code for linear search in java!

### ISSUE THREAD

**Issue by Ayush7-BIT** [Ayush7-BIT/turbo-robot#4]
Add code for linear search in java!

**Comment by IngaleChinmay04** [comment]
I'm interested in doing it! Can you assign this to me?

**Comment by ishanki19-pixel** [comment]
I have created PR for this issue, please verify #10

**Comment by Turbo-dot** [comment]
Hey @Ayush7-BIT, I am interested in this issue, can you assign this issue to me?

**Comment by harshitarai24** [comment]
Hey @Ayush7-BIT, I am interested in doing it , can you assign this issue to me?
