### ISSUE TITLE
Add code for binary search in java!!

### ISSUE THREAD

**Issue by Ayush7-BIT** [Ayush7-BIT/turbo-robot#5]
Add code for binary search in java!!

**Comment by IngaleChinmay04** [comment]
I'm interested in doing it! Can you assign this to me?

**Comment by ishanki19-pixel** [comment]
@Ayush7-BIT I have added a new algo for merge sort, please do consider that for hacktoberfest !

**Comment by Turbo-dot** [comment]
Hey @Ayush7-BIT I am interested in this issue, kindly do assign me?

**Comment by ahemadrazak11** [comment]
Hi @Ayush7-BIT  I'm interested to solve this issue. you can assign to me.

**Comment by Bhuvilol** [comment]
Hey @Ayush7-BIT I am able to solve this query. Kindly assign this to me

**Comment by Satyam-nitp** [comment]
can you assign this to me @Ayush7-BIT

**Comment by krayush7707** [comment]
Hey @Ayush7-BIT I think i can do this. Can you assign this to me?

**Comment by monurajputrko** [comment]
Hey @Ayush7-BIT i can do this. Can you assign this to me?

**Comment by NISHKARSHbaghel** [comment]
I would really like to be assigned to this issue even tho I will be honest about my skills... i'm quite new to this open source world. But It would be great start for me.

**Comment by Saket22-CS** [comment]
Hey @Ayush7-BIT  I am interested in this issue, kindly do assign me?

**Comment by sourav349** [comment]
Hey @Ayush7-BIT, I am interested in this issue, and  able to solve this query. Kindly assign this to me.

**Comment by Mustafa1765** [comment]
Hi @Ayush7-BIT I'm interested to solve this issue. you can assign to me.
thanking u regards Mustafa 
i do follow your youtube channel for open source contribution in hithub

**Comment by alikita** [comment]
hey@Ayush7-BIT, I am interested in this issue , can you assign this issue to me

**Comment by ARP-WorkerHack1** [comment]
I'm interested in doing it! Can you assign this to me?

**Comment by SujitSakore** [comment]
Hey @Ayush7-BIT I think i can do this. Can you assign this to me?

**Comment by manishraj27** [comment]
Hi @Ayush7-BIT,

I've made a contribution to address this issue with pull request #114: "Create BinarySearch.java". 
The pull request implements a binary search algorithm with a unique feature of tracking the number of comparisons made during the search. This addition could be useful for algorithm analysis and educational purposes.

I'd appreciate if you could review the changes when you have a moment. Please let me know if any modifications are needed.

Thank you!d
